name: Supply Chain Scans and Checks

on: [pull_request, workflow_dispatch]

jobs:
  detect-build-system:
    runs-on: ubuntu-latest

    steps:
    - name: Detect Build System
      run: |
        if [[ -f "Cargo.toml" ]]; then
          echo "Rust - Cargo"
          echo "::set-output name=build_system::Rust - Cargo"
        elif [[ -f "Makefile" ]]; then
          echo "Make"
          echo "::set-output name=build_system::Make"
        elif [[ -f "build.gradle" ]]; then
          echo "Java - Gradle"
          echo "::set-output name=build_system::Java - Gradle"
        elif [[ -f "pom.xml" ]]; then
          echo "Java - Maven"
          echo "::set-output name=build_system::Java - Maven"
        else
          echo "Unable to detect build system."
          echo "::set-output name=build_system::Unable to detect build system."
        fi
    - name: Print Build System
      run: echo "Build system: ${{ steps.detect-build-system.outputs.build_system }}"
