name: Supply Chain Scans and Checks

on: [pull_request, push, workflow_dispatch]

jobs:
  dependency-review:
    if: ${{ contains(fromJSON('["push", "pull_request", "workflow_dispatch"]'), github.event_name) }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review PR'
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@v2
      - name: 'Dependency Review Push'
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/dependency-review-action@v2        
        with:
          base-ref: ${{github.ref}}~1
          head-ref: ${{github.ref}}
  detect-build-system:
    runs-on: ubuntu-latest
    steps:
    - name: Detect Build System
      id: detect-build-system
      run: |
        if [[ -f "Cargo.toml" ]]; then
          echo "Rust - Cargo"
          echo "build_system=Rust - Cargo" >> $GITHUB_OUTPUT
        elif [[ -f "Makefile" ]]; then
          echo "Make"
          echo "build_system=Make" >> $GITHUB_OUTPUT
        elif [[ -f "build.gradle" ]]; then
          echo "Java - Gradle"
          echo "build_system=Java - Gradle" >> $GITHUB_OUTPUT
        elif [[ -f "pom.xml" ]]; then
          echo "Java - Maven"        
          echo "build_system=Java - Maven" >> $GITHUB_OUTPUT
        else
          echo "Unable to detect build system."
          echo "build_system=N/A" >> $GITHUB_OUTPUT
        fi
    - name: Print Build System
      run: echo "Build system:${{ steps.detect-build-system.outputs.build_system }}"


